import HOME from "@/lib/site/home/home.html?raw";
import { GA_HOSTS, GA_ID } from "@/lib/analytics/ga";
import { db } from "@/lib/db";
import { bnplEnabled } from "@/lib/payments/bnpl";
import { topFaqs } from "@/lib/site/faq";
import { INDUSTRIES } from "@/lib/site/industries";
import { getLivePrices } from "@/lib/site/livePrices";
import { homeBlocks, homeValues, renderHome, type HomeReview } from "@/lib/site/home/render";
import { HOME_TRACK_SCRIPT } from "@/lib/site/home/track";

// The homepage: the scroll-driven 3D city. It is a self-contained page (its own fonts, styles and script, served from
// public/assets/experience/), generated by build-site.mjs in the Signal repo's showcase/ folder, so it is served as-is
// rather than through the React layout. Its prices, reviews and FAQ come from the same rows as the price list, checkout
// and /faq, refreshed on the same 60-second cycle. The previous homepage is kept at /classic.
export const revalidate = 60;

// Same Google Analytics rules as components/analytics/GoogleAnalytics.tsx: live site only, never under Do Not Track.
const ga = /^G-[A-Z0-9]+$/.test(GA_ID)
  ? `<script>(function(){if(${JSON.stringify(GA_HOSTS)}.indexOf(location.hostname)<0)return;if(navigator.doNotTrack==="1"||window.doNotTrack==="1")return;
window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments);};
gtag("js",new Date());gtag("config","${GA_ID}",{allow_google_signals:false,allow_ad_personalization_signals:false});
addEventListener("load",function(){var s=document.createElement("script");s.async=true;s.src="https://www.googletagmanager.com/gtag/js?id=${GA_ID}";document.head.appendChild(s);});})();</script>\n`
  : "";

/** Reviews customers allowed us to publish (4 stars and up), as on the previous homepage. None if the database can't be reached. */
async function publishedReviews(): Promise<HomeReview[]> {
  try {
    return await db.review.findMany({
      where: { canPublish: true, rating: { gte: 4 } },
      orderBy: { createdAt: "desc" },
      take: 3,
      select: { rating: true, testimonial: true, text: true },
    });
  } catch {
    return [];
  }
}

export async function GET() {
  const [prices, reviews] = await Promise.all([getLivePrices(), publishedReviews()]);
  const blocks = homeBlocks({
    reviews,
    faqs: topFaqs({ bnpl: bnplEnabled(), prices }),
    industries: INDUSTRIES.map(({ slug, name }) => ({ slug, name })),
  });
  const page = renderHome(HOME, homeValues(prices), blocks).replace("</head>", () => `${ga}</head>`).replace("</body>", () => `${HOME_TRACK_SCRIPT}</body>`);
  return new Response(page, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
